export const GameErrors = {
	ROOM_DESTROYED_PLAYER_QUIT: 'ROOM_DESTROYED_PLAYER_QUIT',
	ROOM_ALREADY_STARTED: 'ROOM_ALREADY_STARTED',
	ROOM_FULL: 'ROOM_FULL',
	ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
	ROOM_NOT_INITED: 'ROOM_NOT_INITED',
};
