import { randomArrayElement } from "../random";

enum WordGender {
	MASCULINE = 0,
	FEMININE = 1,
	NEUTER = 2
}

const randomNouns: [string, WordGender][] = [
    ["Křeček",		WordGender.MASCULINE],
    ["Čůza",		WordGender.FEMININE],
    ["Soused",		WordGender.MASCULINE],
    ["Čurina",		WordGender.FEMININE],
    ["Hajzl",		WordGender.MASCULINE],
    ["Kravka",		WordGender.FEMININE],
    ["Fotr",		WordGender.MASCULINE],
    ["Piksla",		WordGender.FEMININE],
    ["Blbec",		WordGender.MASCULINE],
    ["Sukně",		WordGender.FEMININE],
    ["Pižmo",		WordGender.NEUTER],
    ["Houska",		WordGender.FEMININE],
    ["Borec",		WordGender.MASCULINE],
    ["Šoumen",		WordGender.MASCULINE],
    ["Hadr",		WordGender.MASCULINE],
    ["Nádobí",		WordGender.NEUTER],
    ["Vopruz",		WordGender.MASCULINE],
    ["Kraksna",		WordGender.FEMININE],
    ["Huba",		WordGender.FEMININE],
    ["Špek",		WordGender.MASCULINE],
    ["Kostka",		WordGender.FEMININE],
    ["Fajfka",		WordGender.FEMININE],
    ["Kapřík",		WordGender.MASCULINE],
    ["Čudlík",		WordGender.MASCULINE],
    ["Čuba",		WordGender.FEMININE],
    ["Vokno",		WordGender.NEUTER],
    ["Chcípák",		WordGender.MASCULINE],
    ["Teta",		WordGender.FEMININE],
    ["Fízl",		WordGender.MASCULINE],
    ["Frnda",		WordGender.FEMININE],
    ["Pařez",		WordGender.MASCULINE],
    ["Kráva",		WordGender.FEMININE],
    ["Vořech",		WordGender.MASCULINE],
    ["Lopata",		WordGender.FEMININE],
    ["Mařena",		WordGender.FEMININE],
    ["Známost",		WordGender.FEMININE],
    ["Koště",		WordGender.NEUTER],
    ["Kocour",		WordGender.MASCULINE],
    ["Tlusťoch",	WordGender.MASCULINE],
    ["Plechovka",	WordGender.FEMININE],
    ["Žumpa",		WordGender.FEMININE],
    ["Buldozer",	WordGender.MASCULINE],
    ["Čůrák",		WordGender.MASCULINE],
    ["Nadílka",		WordGender.FEMININE],
    ["Žrádlo",		WordGender.NEUTER],
    ["Buchta",		WordGender.FEMININE],
    ["Dement",		WordGender.MASCULINE],
    ["Kotlík",		WordGender.MASCULINE],
    ["Roura",		WordGender.FEMININE],
    ["Kámoš",		WordGender.MASCULINE],
    ["Nanáč",		WordGender.MASCULINE],
    ["Šašek",		WordGender.MASCULINE],
    ["Opice",		WordGender.FEMININE],
    ["Krám",		WordGender.MASCULINE],
    ["Pívo",		WordGender.NEUTER],
    ["Pichna",		WordGender.FEMININE],
    ["Flákač",		WordGender.MASCULINE],
    ["Drzoun",		WordGender.MASCULINE],
    ["Matrač",		WordGender.MASCULINE],
    ["Popelnice",	WordGender.FEMININE],
    ["Kopýtko",		WordGender.NEUTER],
    ["Móresy",		WordGender.NEUTER],
    ["Špunt",		WordGender.MASCULINE],
    ["Zmetek",		WordGender.MASCULINE],
    ["Švestka",		WordGender.FEMININE],
    ["Pohroma",		WordGender.FEMININE],
    ["Zázrak",		WordGender.MASCULINE],
    ["Blondýna",	WordGender.FEMININE],
    ["Koťátko",		WordGender.NEUTER],
    ["Prachy",		WordGender.NEUTER],
    ["Čokl",		WordGender.MASCULINE],
    ["Pytel",		WordGender.MASCULINE],
    ["Matrace",		WordGender.FEMININE],
    ["Blázen",		WordGender.MASCULINE],
    ["Kalhoty",		WordGender.FEMININE],
    ["Výstřik",		WordGender.MASCULINE],
    ["Důchodce",	WordGender.MASCULINE],
    ["Tyčka",		WordGender.FEMININE],
    ["Šmelina",		WordGender.FEMININE],
    ["Troska",		WordGender.FEMININE],
    ["Kalich",		WordGender.MASCULINE],
    ["Svačina",		WordGender.FEMININE],
    ["Dršťka",		WordGender.FEMININE],
    ["Brusle",		WordGender.FEMININE],
    ["Šlupka",		WordGender.FEMININE],
    ["Hejhula",		WordGender.MASCULINE],
    ["Parazit",		WordGender.MASCULINE],
    ["Králík",		WordGender.MASCULINE],
    ["Vopice",		WordGender.FEMININE],
    ["Hrníček",		WordGender.MASCULINE],
    ["Bůček",		WordGender.MASCULINE],
    ["Chlast",		WordGender.MASCULINE],
    ["Prase",		WordGender.NEUTER],
    ["Babizna",		WordGender.FEMININE],
    ["Piha",		WordGender.FEMININE],
    ["Vykuk",		WordGender.MASCULINE],
    ["Mrkev",		WordGender.FEMININE],
    ["Chorobopis",	WordGender.MASCULINE],
    ["Šprt",		WordGender.MASCULINE],
    ["Hnůj",		WordGender.MASCULINE],
    ["Rovnice",		WordGender.FEMININE],
    ["Limoška",		WordGender.FEMININE],
    ["Šunka",		WordGender.FEMININE],
    ["Chalupa",		WordGender.FEMININE],
    ["Řepka",		WordGender.FEMININE],
    ["Báchor",		WordGender.MASCULINE],
    ["Klobása",		WordGender.FEMININE],
    ["Pepa",		WordGender.MASCULINE],
    ["Facka",		WordGender.FEMININE],
    ["Had",			WordGender.MASCULINE],
    ["Žiletka",		WordGender.FEMININE],
    ["Švindl",		WordGender.MASCULINE],
    ["Kudla",		WordGender.FEMININE],
    ["Drákula",		WordGender.MASCULINE],
    ["Pako",		WordGender.NEUTER],
    ["Klika",		WordGender.FEMININE],
    ["Muž",			WordGender.MASCULINE],
    ["Šnůra",		WordGender.FEMININE],
    ["Hovno",		WordGender.NEUTER],
    ["Pec",			WordGender.FEMININE],
    ["Magor",		WordGender.MASCULINE],
    ["Kapusta",		WordGender.FEMININE],
    ["Suchar",		WordGender.MASCULINE],
    ["Balík",		WordGender.MASCULINE],
    ["Koryto",		WordGender.NEUTER],
    ["Trenýrky",	WordGender.FEMININE],
    ["Moucha",		WordGender.FEMININE],
    ["Jitrnice",	WordGender.FEMININE],
    ["Rukavice",	WordGender.FEMININE],
    ["Mezek",		WordGender.MASCULINE],
    ["Ježek",		WordGender.MASCULINE],
    ["Větrák",		WordGender.MASCULINE],
    ["Řeřicha",		WordGender.FEMININE],
    ["Bordel",		WordGender.MASCULINE],
    ["Rádio",		WordGender.NEUTER],
    ["Kohout",		WordGender.MASCULINE],
    ["Cukr",		WordGender.MASCULINE],
    ["Lízátko",		WordGender.NEUTER],
    ["Bubák",		WordGender.MASCULINE],
    ["Výkal",		WordGender.MASCULINE]
]



export function getRandomNoun() {
	return randomArrayElement(randomNouns);
}

12+13
